name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install all dependencies
        run: npm ci

      - name: Check text spelling with yaspeller
        run: npm run spell

      - name: Lint code with eslint
        run: npm run lint

      - name: Run unit-tests
        run: npx jest
